name: Github Actions Maven Build 

on:
  push:
    branches: [ master ]
jobs:

  build-on-ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from GitHub 
        uses: actions/checkout@v2
      - name: content of current directory
        run:
          mkdir installed
      - name: Step 2 - Creating folder 
        run: |
          cd installed
          echo 'saad' >1.yaml
          cd ..

      - name: Step 3 - Persist workflow data as artificats
        uses: actions/upload-artifact@v2
        with:
          name: github-actions-artifact
          path: installed
      - name: content of current directory
        run:
          ls -al
